# Decision Tree Classifier

#### Importing Libraries

In [4]:
import pandas as pd # data analytical library
import numpy as np #fast linear algebra
import matplotlib.pyplot as plt #visualization
import seaborn as sns #statistical visualization

#### Importing dataset

In [5]:
df=pd.read_csv("train.csv")

#### Viewing the first 5 rows

In [6]:
df.head()

UniqueID  disbursed_amount  asset_cost    ltv  branch_id  supplier_id  \
0    420825             50578       58400  89.55         67        22807   
1    537409             47145       65550  73.23         67        22807   
2    417566             53278       61360  89.63         67        22807   
3    624493             57513       66113  88.48         67        22807   
4    539055             52378       60300  88.39         67        22807   

   manufacturer_id  Current_pincode_ID Date.of.Birth Employment.Type  ...  \
0               45                1441      01-01-84        Salaried  ...   
1               45                1502      31-07-85   Self employed  ...   
2               45                1497      24-08-85   Self employed  ...   
3               45                1501      30-12-93   Self employed  ...   
4               45                1495      09-12-77   Self employed  ...   

  SEC.SANCTIONED.AMOUNT  SEC.DISBURSED.AMOUNT  PRIMARY.INSTAL.AMT  \
0                     0                     0                   0   
1                     0                     0                1991   
2                     0                     0                   0   
3                     0                     0                  31   
4                     0                     0                   0   

   SEC.INSTAL.AMT  NEW.ACCTS.IN.LAST.SIX.MONTHS  \
0               0                             0   
1               0                             0   
2               0                             0   
3               0                             0   
4               0                             0   

   DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS  AVERAGE.ACCT.AGE  \
0                                    0         0yrs 0mon   
1                                    1        1yrs 11mon   
2                                    0         0yrs 0mon   
3                                    0         0yrs 8mon   
4                                    0         0yrs 0mon   

   CREDIT.HISTORY.LENGTH  NO.OF_INQUIRIES  loan_default  
0              0yrs 0mon                0             0  
1             1yrs 11mon                0             1  
2              0yrs 0mon                0             0  
3              1yrs 3mon                1             1  
4              0yrs 0mon                1             1  

[5 rows x 41 columns]

#### Checking for Missing values

In [7]:
df.isnull().sum()

UniqueID                                  0
disbursed_amount                          0
asset_cost                                0
ltv                                       0
branch_id                                 0
supplier_id                               0
manufacturer_id                           0
Current_pincode_ID                        0
Date.of.Birth                             0
Employment.Type                        7661
DisbursalDate                             0
State_ID                                  0
Employee_code_ID                          0
MobileNo_Avl_Flag                         0
Aadhar_flag                               0
PAN_flag                                  0
VoterID_flag                              0
Driving_flag                              0
Passport_flag                             0
PERFORM_CNS.SCORE                         0
PERFORM_CNS.SCORE.DESCRIPTION             0
PRI.NO.OF.ACCTS                           0
PRI.ACTIVE.ACCTS                

#### Missing value treatment using Mode imputation

In [8]:
df['Employment.Type']=df['Employment.Type'].fillna(df['Employment.Type'].mode()[0])

In [9]:
df.isnull().sum()

UniqueID                               0
disbursed_amount                       0
asset_cost                             0
ltv                                    0
branch_id                              0
supplier_id                            0
manufacturer_id                        0
Current_pincode_ID                     0
Date.of.Birth                          0
Employment.Type                        0
DisbursalDate                          0
State_ID                               0
Employee_code_ID                       0
MobileNo_Avl_Flag                      0
Aadhar_flag                            0
PAN_flag                               0
VoterID_flag                           0
Driving_flag                           0
Passport_flag                          0
PERFORM_CNS.SCORE                      0
PERFORM_CNS.SCORE.DESCRIPTION          0
PRI.NO.OF.ACCTS                        0
PRI.ACTIVE.ACCTS                       0
PRI.OVERDUE.ACCTS                      0
PRI.CURRENT.BALA

In [48]:
df.info()  ## Basic information regarding the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 233154 entries, 0 to 233153
Data columns (total 41 columns):
 #   Column                               Non-Null Count   Dtype  
---  ------                               --------------   -----  
 0   UniqueID                             233154 non-null  int64  
 1   disbursed_amount                     233154 non-null  int64  
 2   asset_cost                           233154 non-null  int64  
 3   ltv                                  233154 non-null  float64
 4   branch_id                            233154 non-null  int64  
 5   supplier_id                          233154 non-null  int64  
 6   manufacturer_id                      233154 non-null  int64  
 7   Current_pincode_ID                   233154 non-null  int64  
 8   Date.of.Birth                        233154 non-null  object 
 9   Employment.Type                      233154 non-null  object 
 10  DisbursalDate                        233154 non-null  object 
 11  State_ID     

In [49]:
df.columns ## Column names in the dataset

Index(['UniqueID', 'disbursed_amount', 'asset_cost', 'ltv', 'branch_id',
       'supplier_id', 'manufacturer_id', 'Current_pincode_ID', 'Date.of.Birth',
       'Employment.Type', 'DisbursalDate', 'State_ID', 'Employee_code_ID',
       'MobileNo_Avl_Flag', 'Aadhar_flag', 'PAN_flag', 'VoterID_flag',
       'Driving_flag', 'Passport_flag', 'PERFORM_CNS.SCORE',
       'PERFORM_CNS.SCORE.DESCRIPTION', 'PRI.NO.OF.ACCTS', 'PRI.ACTIVE.ACCTS',
       'PRI.OVERDUE.ACCTS', 'PRI.CURRENT.BALANCE', 'PRI.SANCTIONED.AMOUNT',
       'PRI.DISBURSED.AMOUNT', 'SEC.NO.OF.ACCTS', 'SEC.ACTIVE.ACCTS',
       'SEC.OVERDUE.ACCTS', 'SEC.CURRENT.BALANCE', 'SEC.SANCTIONED.AMOUNT',
       'SEC.DISBURSED.AMOUNT', 'PRIMARY.INSTAL.AMT', 'SEC.INSTAL.AMT',
       'NEW.ACCTS.IN.LAST.SIX.MONTHS', 'DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS',
       'AVERAGE.ACCT.AGE', 'CREDIT.HISTORY.LENGTH', 'NO.OF_INQUIRIES',
       'loan_default'],
      dtype='object')

##### Since Decision tree is better for categorical and discrete variables

##### To keep only dicrete columns

In [12]:
list1=[] 
for column in df.columns:
    if len(df[column].unique()) < 30:
        list1.append(column)
        print(list1)

['manufacturer_id']
['manufacturer_id', 'Employment.Type']
['manufacturer_id', 'Employment.Type', 'State_ID']
['manufacturer_id', 'Employment.Type', 'State_ID', 'MobileNo_Avl_Flag']
['manufacturer_id', 'Employment.Type', 'State_ID', 'MobileNo_Avl_Flag', 'Aadhar_flag']
['manufacturer_id', 'Employment.Type', 'State_ID', 'MobileNo_Avl_Flag', 'Aadhar_flag', 'PAN_flag']
['manufacturer_id', 'Employment.Type', 'State_ID', 'MobileNo_Avl_Flag', 'Aadhar_flag', 'PAN_flag', 'VoterID_flag']
['manufacturer_id', 'Employment.Type', 'State_ID', 'MobileNo_Avl_Flag', 'Aadhar_flag', 'PAN_flag', 'VoterID_flag', 'Driving_flag']
['manufacturer_id', 'Employment.Type', 'State_ID', 'MobileNo_Avl_Flag', 'Aadhar_flag', 'PAN_flag', 'VoterID_flag', 'Driving_flag', 'Passport_flag']
['manufacturer_id', 'Employment.Type', 'State_ID', 'MobileNo_Avl_Flag', 'Aadhar_flag', 'PAN_flag', 'VoterID_flag', 'Driving_flag', 'Passport_flag', 'PERFORM_CNS.SCORE.DESCRIPTION']
['manufacturer_id', 'Employment.Type', 'State_ID', 'Mobil

In [50]:
cols=['manufacturer_id', 'Employment.Type', 'State_ID', 'MobileNo_Avl_Flag', 'Aadhar_flag', 'PAN_flag', 'VoterID_flag', 'Driving_flag', 'Passport_flag', 'PERFORM_CNS.SCORE.DESCRIPTION', 'PRI.OVERDUE.ACCTS', 'SEC.ACTIVE.ACCTS', 'SEC.OVERDUE.ACCTS', 'NEW.ACCTS.IN.LAST.SIX.MONTHS', 'DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS', 'NO.OF_INQUIRIES', 'loan_default']

In [51]:
data=df[cols]

In [52]:
data.head()

manufacturer_id Employment.Type  State_ID  MobileNo_Avl_Flag  Aadhar_flag  \
0               45        Salaried         6                  1            1   
1               45   Self employed         6                  1            1   
2               45   Self employed         6                  1            1   
3               45   Self employed         6                  1            1   
4               45   Self employed         6                  1            1   

   PAN_flag  VoterID_flag  Driving_flag  Passport_flag  \
0         0             0             0              0   
1         0             0             0              0   
2         0             0             0              0   
3         0             0             0              0   
4         0             0             0              0   

  PERFORM_CNS.SCORE.DESCRIPTION  PRI.OVERDUE.ACCTS  SEC.ACTIVE.ACCTS  \
0   No Bureau History Available                  0                 0   
1                 I-Medium Risk                  1                 0   
2   No Bureau History Available                  0                 0   
3              L-Very High Risk                  0                 0   
4   No Bureau History Available                  0                 0   

   SEC.OVERDUE.ACCTS  NEW.ACCTS.IN.LAST.SIX.MONTHS  \
0                  0                             0   
1                  0                             0   
2                  0                             0   
3                  0                             0   
4                  0                             0   

   DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS  NO.OF_INQUIRIES  loan_default  
0                                    0                0             0  
1                                    1                0             1  
2                                    0                0             0  
3                                    0                1             1  
4                                    0                1             1

#### Label encoding


In [53]:
import sklearn.preprocessing as pre

In [54]:
le=pre.LabelEncoder()

In [18]:
cat_df=data.select_dtypes(include='object')  ## checking for categorical variables
cat_df.head()

Employment.Type PERFORM_CNS.SCORE.DESCRIPTION
0        Salaried   No Bureau History Available
1   Self employed                 I-Medium Risk
2   Self employed   No Bureau History Available
3   Self employed              L-Very High Risk
4   Self employed   No Bureau History Available

In [19]:
for x in cat_df:
    data[x]=le.fit_transform(data[x])  ## encoding the categorical variables

<ipython-input-19-675f86c1b7a1>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[x]=le.fit_transform(data[x])


In [20]:
data.head()

manufacturer_id  Employment.Type  State_ID  MobileNo_Avl_Flag  Aadhar_flag  \
0               45                0         6                  1            1   
1               45                1         6                  1            1   
2               45                1         6                  1            1   
3               45                1         6                  1            1   
4               45                1         6                  1            1   

   PAN_flag  VoterID_flag  Driving_flag  Passport_flag  \
0         0             0             0              0   
1         0             0             0              0   
2         0             0             0              0   
3         0             0             0              0   
4         0             0             0              0   

   PERFORM_CNS.SCORE.DESCRIPTION  PRI.OVERDUE.ACCTS  SEC.ACTIVE.ACCTS  \
0                             13                  0                 0   
1                              8                  1                 0   
2                             13                  0                 0   
3                             11                  0                 0   
4                             13                  0                 0   

   SEC.OVERDUE.ACCTS  NEW.ACCTS.IN.LAST.SIX.MONTHS  \
0                  0                             0   
1                  0                             0   
2                  0                             0   
3                  0                             0   
4                  0                             0   

   DELINQUENT.ACCTS.IN.LAST.SIX.MONTHS  NO.OF_INQUIRIES  loan_default  
0                                    0                0             0  
1                                    1                0             1  
2                                    0                0             0  
3                                    0                1             1  
4                                    0                1             1

#### Model Building

In [21]:
from sklearn import tree, metrics, model_selection, preprocessing

In [22]:
tree.DecisionTreeClassifier()

DecisionTreeClassifier()

In [23]:
import sklearn.preprocessing as pre
import sklearn.model_selection as ms

In [24]:
features=data.drop('loan_default',axis=1)

In [25]:
outcome=data['loan_default']

#### Min max scaling

In [26]:
feature_scale=pre.minmax_scale(features)

#### Train test split

In [27]:
x_train,x_test,y_train,y_test=ms.train_test_split(feature_scale,outcome,test_size=0.3,random_state=12356)

#### Model

In [28]:
dtree = tree.DecisionTreeClassifier(criterion='entropy',
                                   random_state=5)
dtree.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=5)

In [29]:
y_pred = dtree.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

#### Model Performance

In [30]:
dtree.score(x_test,y_test)

0.7582884183739117

In [31]:
dtree.score(x_train,y_train) ## overfitting

0.8244928219990564

##### Model Evaluation

In [32]:
import sklearn.metrics as mt

In [33]:
mt.confusion_matrix(y_test,y_pred)

array([[51989,  2755],
       [14152,  1051]], dtype=int64)

## CART implementation and finding best parameters using GridSearchCV

In [38]:
cart = tree.DecisionTreeClassifier(max_features="auto", max_depth=6,random_state=20)
cart.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=6, max_features='auto', random_state=20)

In [39]:
y_cart_pred = cart.predict(x_test)
y_cart_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [40]:
mt.confusion_matrix(y_test,y_cart_pred)

array([[54723,    21],
       [15188,    15]], dtype=int64)

array([[51989,  2755],
       [14152,  1051]], dtype=int64)

In [41]:
para={"max_depth":[4,6,8,10,12,14],
      "random_state":[5,10,15,20,25,20],
     "max_features":["auto", "sqrt", "log2"]
     }
para

{'max_depth': [4, 6, 8, 10, 12, 14],
 'random_state': [5, 10, 15, 20, 25, 20],
 'max_features': ['auto', 'sqrt', 'log2']}

In [42]:
cart_CV = tree.DecisionTreeClassifier()

In [43]:
grid=ms.GridSearchCV(cart_CV,para)

In [44]:
grid.fit(x_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [4, 6, 8, 10, 12, 14],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'random_state': [5, 10, 15, 20, 25, 20]})

In [45]:
pd.DataFrame(grid.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0         0.053921      0.002718         0.004186        0.000399   
1         0.061823      0.006424         0.004177        0.000380   
2         0.071112      0.008813         0.004384        0.000484   
3         0.061178      0.008365         0.004585        0.000796   
4         0.055416      0.002052         0.004186        0.000399   
..             ...           ...              ...             ...   
103       0.132933      0.027609         0.008908        0.001360   
104       0.118247      0.001522         0.007362        0.000498   
105       0.116748      0.006004         0.007707        0.000648   
106       0.113331      0.004759         0.007453        0.000421   
107       0.122719      0.016055         0.007770        0.000748   

    param_max_depth param_max_features param_random_state  \
0                 4               auto                  5   
1                 4               auto                 10   
2                 4               auto                 15   
3                 4               auto                 20   
4                 4               auto                 25   
..              ...                ...                ...   
103              14               log2                 10   
104              14               log2                 15   
105              14               log2                 20   
106              14               log2                 25   
107              14               log2                 20   

                                                params  split0_test_score  \
0    {'max_depth': 4, 'max_features': 'auto', 'rand...           0.783040   
1    {'max_depth': 4, 'max_features': 'auto', 'rand...           0.783040   
2    {'max_depth': 4, 'max_features': 'auto', 'rand...           0.783040   
3    {'max_depth': 4, 'max_features': 'auto', 'rand...           0.783040   
4    {'max_depth': 4, 'max_features': 'auto', 'rand...           0.782918   
..                                                 ...                ...   
103  {'max_depth': 14, 'max_features': 'log2', 'ran...           0.778659   
104  {'max_depth': 14, 'max_features': 'log2', 'ran...           0.777311   
105  {'max_depth': 14, 'max_features': 'log2', 'ran...           0.777495   
106  {'max_depth': 14, 'max_features': 'log2', 'ran...           0.778567   
107  {'max_depth': 14, 'max_features': 'log2', 'ran...           0.777495   

     split1_test_score  split2_test_score  split3_test_score  \
0             0.782979           0.783034           0.783064   
1             0.783040           0.783064           0.783064   
2             0.783040           0.783064           0.783064   
3             0.782948           0.783095           0.783034   
4             0.783040           0.783064           0.782850   
..                 ...                ...                ...   
103           0.779027           0.778254           0.778959   
104           0.778506           0.777948           0.778867   
105           0.778476           0.778775           0.778040   
106           0.777894           0.778622           0.779388   
107           0.778476           0.778775           0.778040   

     split4_test_score  mean_test_score  std_test_score  rank_test_score  
0             0.783034         0.783030        0.000028               19  
1             0.783034         0.783049        0.000013                7  
2             0.783034         0.783049        0.000013                7  
3             0.783064         0.783036        0.000049               13  
4             0.783034         0.782981        0.000083               28  
..                 ...              ...             ...              ...  
103           0.778285         0.778637        0.000325               94  
104           0.778499         0.778226        0.000544              100  
105           0.778224         0.778202        0.000431              103  

In [46]:
grid.best_params_

{'max_depth': 6, 'max_features': 'auto', 'random_state': 20}

In [47]:
grid.best_score_

0.7830546478168483